### ISSUE TITLE
Reader modes renaming

### ISSUE THREAD

**Issue by alkumaish** [Suwayomi/Tachidesk-VUI#58]
The way naming done in Tachidesk-WebUI makes more sense. 

Current name ->  Expected name (according to its behaviour)

RTL ->  RTL (Continuous Vertical)
LTR ->  LTR (Continuous Vertical)
SinglePage -> Webtoon
Vertical -> this one is ok as it is.

Adding Single page (RTL/LTR) a la manga style is needed for manga readers on mobile/vertical screens.

**Comment by Robonau** [comment]
reader has changed significantly since this issue was made
it is now:

`LTR`: 2 pages side by side in LTR
`RTL`: 2 pages side by side in RTL
`SinglePage`: same as ltr just 1 page and not 2
`Vertical`: continuous scrolling mode

the difference between `SinglePage` and `Vertical` is how scale works, `SinglePage` is scale to height of screen, `Vertical` scales to width

single page `LTR` or `RTL` are just `SinglePage`
